import type { Adapter, ExportResult, ExportedFile, ExportWarning } from "./index.js";
import { resolvePath, localeCollisionWarnings } from "./index.js";
import { resolveLocaleToken, type LocaleCase } from "./options.js";
import { gettextPluralForms, categoriesFor } from "../plurals.js";
import { withLiterals, isIcuPluralOrSelect } from "../placeholders.js";
import type { State, OutputConfig } from "../schema.js";

// Escape a string for a PO double-quoted literal (backslash first).
function poString(s: string): string {
  return '"' + s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(/\r/g, "\\r") + '"';
}

// Render our neutral {arg} count token as printf %d (gettext convention).
// Literal spans ('{site}') emit their content verbatim; printf's % sigil is
// escaped to %% in all non-placeholder text — done before the {arg}->%d split so
// the introduced %d is never double-escaped. Split on the literal token so a
// regex-special arg is handled safely.
function toGettext(body: string, arg: string): string {
  const gap = (text: string): string => text.replace(/%/g, "%%").split(`{${arg}}`).join("%d");
  if (isIcuPluralOrSelect(body)) return gap(body);
  return withLiterals(body, gap, (lit) => lit.replace(/%/g, "%%"));
}

const DEFAULT_LOCALE_CASE: LocaleCase = "lower-hyphen";

export const gettextPo: Adapter = {
  name: "gettext-po",
  capabilities: {
    plural: "native",
    select: "lossy",
    nesting: "flat",
    metadata: false,
    placeholderStyle: "printf",
    fileGrouping: "per-locale",
  },
  defaultLocaleCase: DEFAULT_LOCALE_CASE,
  export(state: State, output: OutputConfig): ExportResult {
    const warnings: ExportWarning[] = [];
    warnings.push(...localeCollisionWarnings(output, state.config.locales, DEFAULT_LOCALE_CASE));
    const files: ExportedFile[] = [];
    const sourceLocale = state.config.sourceLocale;
    const keys = Object.keys(state.keys).sort();
    for (const locale of state.config.locales) {
      const token = resolveLocaleToken(output, locale, DEFAULT_LOCALE_CASE);
      const { nplurals, expr, sampled } = gettextPluralForms(locale);
      const cats = categoriesFor(locale);
      const blocks: string[] = [
        [
          'msgid ""',
          'msgstr ""',
          poString("Content-Type: text/plain; charset=UTF-8\n"),
          poString(`Language: ${token}\n`),
          poString(`Plural-Forms: nplurals=${nplurals}; plural=${expr};\n`),
        ].join("\n"),
      ];
      let emittedPlural = false;
      for (const key of keys) {
        const entry = state.keys[key]!;
        const lv = entry.values[locale];
        const src = entry.values[sourceLocale];
        if (entry.plural) {
          emittedPlural = true;
          const arg = entry.plural.arg;
          const srcForms = src?.forms ?? {};
          const lines = [
            `msgctxt ${poString(key)}`,
            // gettext keys a plural on the source singular/plural pair.
            `msgid ${poString(toGettext(srcForms.one ?? srcForms.other ?? "", arg))}`,
            `msgid_plural ${poString(toGettext(srcForms.other ?? "", arg))}`,
          ];
          // msgstr[i] follows this locale's canonical category order, which is
          // the same index mapping gettextPluralForms used for `expr`.
          for (let i = 0; i < nplurals; i++) {
            const cat = cats[i]!;
            const body = lv?.forms?.[cat] ?? lv?.forms?.other ?? "";
            lines.push(`msgstr[${i}] ${poString(toGettext(body, arg))}`);
          }
          blocks.push(lines.join("\n"));
        } else {
          blocks.push(
            [
              `msgctxt ${poString(key)}`,
              // Scalar keys carry no count arg; toGettext still strips literal
              // spans and escapes a literal % to %%.
              `msgid ${poString(toGettext(src?.value ?? "", ""))}`,
              `msgstr ${poString(toGettext(lv?.value ?? "", ""))}`,
            ].join("\n"),
          );
        }
      }
      if (sampled && emittedPlural) {
        warnings.push({
          code: "unsupported-metadata",
          key: "",
          locale,
          message: `Plural-Forms for "${locale}" is generated by sampling counts 0–200; verify behaviour for larger numbers.`,
        });
      }
      files.push({ path: resolvePath(output.path, token), contents: blocks.join("\n\n") + "\n" });
    }
    return { files, warnings };
  },
};
